package ua.com.validation;

public interface ValidationMassages {

	String EMPTY_LOGIN_FIELD = "EMPTY_LOGIN_FIELD";
	String EMPTY_PASSWORD_FIELD = "EMPTY_PASSWORD_FIELD";
	String EMPTY_MAIL_FIELD = "EMPTY_MAIL_FIELD";
	String NAME_ALREADY_EXIST = "NAME_ALREADY_EXIST";
	String MAIL_ALREADY_EXIST = "MAIL_ALREADY_EXIST";
	String NOT_RIGHT_LOGIN_OR_PASSWORD = "NOT_RIGHT_LOGIN_OR_PASSWORD";
	///////////////////////////FOR Category
	String EMPTY_CATEGORY_NAME_FIELD = "EMPTY_CATEGORY_NAME_FIELD";
	String EMPTY_CATEGORY_TYPE_FIELD = "EMPTY_CATEGORY_TYPE_FIELD";
	String EMPTY_CATEGORY_STATUS_FIELD = "EMPTY_CATEGORY_STATUS_FIELD";
	String CATEGORY_NAME_ALREADY_EXIST = "CATEGORY_NAME_ALREADY_EXIST";
	String CATEGORY_TYPE_ALREADY_EXIST = "CATEGORY_TYPE_ALREADY_EXIST";
	String CATEGORY_STATUS_ALREADY_EXIST = "CATEGORY_STATUS_ALREADY_EXIST";
	/////////////////////////FOR Producer
	String EMPTY_Producer_FIELD = "EMPTY_Producer_FIELD";
	String EMPTY_COUNTRY_FIELD = "EMPTY_COUNTRY_FIELD";
	String Producer_ALREADY_EXIST = "Producer_ALREADY_EXIST";
	/////////////////////////FOR Commodity
	String COMMODITY_ALREADY_EXIST = "COMMODITY_ALREADY_EXIST";
}
